apiVersion: apps/v1
kind: Deployment
metadata:
  name: newmyapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newmyapp
  template:
    metadata:
      labels:
        app: newmyapp
    spec:
      containers:
      - name: newmyapp
        image: viji2553/newmyapp:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: newmyapp
  namespace: default
spec:
  type: NodePort
  selector:
    app: newmyapp
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000  # Expose via NodePort
